Repository cse110-sp24-group33/cse110-sp24-group33, pull requests merged in 2024-06, with the labels that each got.

#61 wiki generation
  .github/workflows/generate-docs.yml
  .github/workflows/generate-wiki.yml
Labels: infrastructure

#65 localStorage.util unit tests
  source/__tests__/e2e/userFlow.puppeteer.test.js
  source/__tests__/unit/date.util.test.js
  source/__tests__/unit/localstorage.util.test.js
  source/__tests__/unit/main.index.test.js
  source/package.json
  source/public/scripts/localstorage.util.js
  source/public/scripts/main.index.js
  source/public/scripts/main.journal.js
Labels: testing

#63 homepage CSS
  source/public/index.html
  source/public/styles/styles.css
Labels: feature

#71 added tests for all functions in date.util.js
  source/__tests__/unit/date.util.test.js
Labels: testing

#70 integrate projects as task tags
  source/public/journal.html
  source/public/scripts/localstorage.util.js
  source/public/scripts/main.journal.js
  source/public/styles/styles.css
Labels: feature
